language: objective-c
osx_image: xcode7.3
sudo: false
notifications:
  email: false
before_install:
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
  - set -o pipefail && xcodebuild test -workspace Example/Wia.xcworkspace -scheme Wia-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
  - pod lib lint --quick
